### ISSUE TITLE
Can’t get pickup date in Locale French 

### ISSUE THREAD

**Issue by oxamafia** [Der-Henning/tgtg#468] opened 2024-02-19 22:07 UTC
Hello
Firstly I do thank you for the great job! It’s really impressive!
I am trying to get it work with the French locale and I’ve put the locale variable to fr_FR, running with a docker under Synology. 
but the pickup date is still in English language (eg today or tomorrow for example). 
How can I translate these words to French equivalent?
Thanks for your precious help

**Comment by p3t3r** [comment] 2024-02-22 08:37
I have the same issue with dutch (using nl_nl ), I also get "today" for instance.

**Comment by Der-Henning** [comment] 2024-02-24 17:13
Hi @oxamafia.
Thank you for the issue report.
The bug should be fixed in version 1.20.3. Can you confirm that the issue is resolved?

**Comment by oxamafia** [comment] 2024-02-25 16:03
Hi @Der-Henning 
That worked for me! Thank you very much!!!!

**Closed** 2024-02-25 16:49 UTC
