### ISSUE TITLE
TGTG API ERROR

### ISSUE THREAD

**Issue by Wolbaal** [Der-Henning/tgtg#246] opened 2023-01-17 17:30 UTC
Hi, have a new problem and Tgtg stopped:

![image](https://user-images.githubusercontent.com/103828692/212970166-c4e9f077-8d2f-4d2d-adb9-83cc7c4d973d.jpeg)

**Comment by GrappaTV** [comment] 2023-01-18 08:00
I have the same problem since last night (17-1). Was still running 1.13. I upgraded to 1.14.5 after error occurred but it generates the same error (and stops tgtg).

**Comment by Der-Henning** [comment] 2023-01-18 17:18
Hi @Wolbaal and @GrappaTV.
On startup, the scanner tries to verify the provided configuration by login in on the tgtg API. On failure, the scanner stops. This is the case as you receive the 403 captcha error.

As the error is not caused by a configuration error the scanner should try to resolve the captcha error and retry it after some time. I consider this a bug and will try to resolve it as soon as possible. Thank you for your report.

**Comment by Wolbaal** [comment] 2023-01-18 18:18
Hi,

Thanks for reply. It seems that it doesn't try to resolve the captcha there it stopped the program. Running 1.14.5

**Comment by Wolbaal** [comment] 2023-01-19 07:54
Is there a possibility to make the 1.14.4 as pull-down again?

**Comment by Wolbaal** [comment] 2023-01-19 09:12
Or can I give in a comment instead of "latest" ?

**Comment by Der-Henning** [comment] 2023-01-19 13:42
Using docker you can always specify a version by setting the image tag
````yml
image: derhenning/tgtg:v1.14.4
````
See https://hub.docker.com/r/derhenning/tgtg/tags for all available tags.

**Comment by Wolbaal** [comment] 2023-01-19 14:16
Hi, thanks for reply! I did this in stack and works for me to downgrade to version 1.14.3

**Comment by prashantsomashekar** [comment] 2023-01-20 05:42
I also received this.  I wanted to downgrade and noticed it was hanging.  Cleared out the tokens in the conf. to start anew and now hitting this: 
requests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Der-Henning/tgtg/releases/latest

Full stack trace:
Traceback (most recent call last):
  File "main.py", line 267, in <module>
  File "main.py", line 36, in main
  File "main.py", line 170, in _get_version_info
  File "main.py", line 199, in _get_new_version
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Der-Henning/tgtg/releases/latest
[6916] Failed to execute script 'main' due to unhandled exception!

**Comment by pershoot** [comment] 2023-01-20 05:46
I also was receiving this and then hanging.  Downgraded and noticed it was hanging after 'new release available'.  Cleared tokens out of conf. to start anew and now hitting this (both .4 and .5):
403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Der-Henning/tgtg/releases/latest

Full stack:
Traceback (most recent call last):
  File "main.py", line 267, in <module>
  File "main.py", line 36, in main
  File "main.py", line 170, in _get_version_info
  File "main.py", line 199, in _get_new_version
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/Der-Henning/tgtg/releases/latest
[6916] Failed to execute script 'main' due to unhandled exception!

**Comment by Der-Henning** [comment] 2023-01-22 15:30
Hello everyone.
I updated the scanner's behavior on 403 captcha errors in release 1.14.6. Any feedback is appreciated!

- The scanner now should not stop if there is a 403 error on startup.
- After a 403 error, the scanner retries 10 times in 10 seconds. Then waits 10 minutes, resets the HTTP session, and retries the request.
- The error messages are much shorter now.

**Comment by pershoot** [comment] 2023-01-22 15:38
Startup and test notification succeeded.  Re-using previous config and just replaced the .exe (Windows).  It does WARN on captcha.
[2023-01-22 10:35:23][tgtg][main.py:_print_welcome_message:233][INFO] 
[2023-01-22 10:35:24][tgtg][tgtg_client.py:_post:171][WARNING] Captcha Error 403!
[2023-01-22 10:35:25][tgtg][notifiers.py:__init__:24][INFO] Activated notifiers:
[2023-01-22 10:35:25][tgtg][notifiers.py:__init__:28][INFO] - IFTTT: _-----_
[2023-01-22 10:35:25][tgtg][scanner.py:__init__:51][INFO] Sending test Notifications ...
[2023-01-22 10:35:25][tgtg][scanner.py:run:165][INFO] Scanner started ...

**Comment by GrappaTV** [comment] 2023-01-22 15:41
Hi Henning,

 

Looks good !   Waiting for the first real message. Looks like we owe you a few beers 😉.

 

BR

Roel

 

[2023-01-22 16:37:31][tgtg][config.py:__init__:118][INFO] Loaded config from C:\TooGoodToGo\scannerRoel\config.ini

[2023-01-22 16:37:31][tgtg][main.py:_print_welcome_message:228][INFO]   ____  ___  ____  ___    ____   ___   __   __ _  __ _  ____  ____  

[2023-01-22 16:37:31][tgtg][main.py:_print_welcome_message:228][INFO]  (_  _)/ __)(_  _)/ __)  / ___) / __) / _\ (  ( \(  ( \(  __)(  _ \ 

[2023-01-22 16:37:31][tgtg][main.py:_print_welcome_message:228][INFO]    )( ( (_ \  )( ( (_ \  \___ \( (__ /    \/    //    / ) _)  )   / 

[2023-01-22 16:37:31][tgtg][main.py:_print_welcome_message:228][INFO]   (__) \___/ (__) \___/  (____/ \___)\_/\_/\_)__)\_)__)(____)(__\_) 

[2023-01-22 16:37:31][tgtg][main.py:_print_welcome_message:229][INFO] 

[2023-01-22 16:37:31][tgtg][main.py:_print_welcome_message:230][INFO] Version 1.14.6

[2023-01-22 16:37:31][tgtg][main.py:_print_welcome_message:231][INFO] ©2022, Henning Merklinger

[2023-01-22 16:37:31][tgtg][main.py:_print_welcome_message:232][INFO] For documentation and support please visit https://github.com/Der-Henning/tgtg

[2023-01-22 16:37:31][tgtg][main.py:_print_welcome_message:233][INFO] 

[2023-01-22 16:37:31][tgtg][tgtg_client.py:_post:171][WARNING] Captcha Error 403!

[2023-01-22 16:37:32][apscheduler.scheduler][base.py:start:166][INFO] Scheduler started

[2023-01-22 16:37:32][tgtg][notifiers.py:__init__:24][INFO] Activated notifiers:

[2023-01-22 16:37:32][tgtg][notifiers.py:__init__:28][INFO] - Telegram: ['999999999']

[2023-01-22 16:37:32][tgtg][scanner.py:__init__:51][INFO] Sending test Notifications ...

[2023-01-22 16:37:33][tgtg][scanner.py:run:165][INFO] Scanner started ...

 

Van: pershoot ***@***.***> 
Verzonden: Sunday, 22 January 2023 16:39
Aan: Der-Henning/tgtg ***@***.***>
CC: GrappaTV ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Der-Henning/tgtg] TGTG API ERROR (Issue #246)

 

Startup and test notification succeeded. Re-using previous config and just replaced the .exe (Windows). It does WARN on captcha.
[2023-01-22 10:35:23][tgtg][main.py:_print_welcome_message:233][INFO]
[2023-01-22 10:35:24][tgtg][tgtg_client.py:_post:171][WARNING] Captcha Error 403!
[2023-01-22 10:35:25][tgtg][notifiers.py:init:24][INFO] Activated notifiers:
[2023-01-22 10:35:25][tgtg][notifiers.py:init:28][INFO] - IFTTT: -----
[2023-01-22 10:35:25][tgtg][scanner.py:init:51][INFO] Sending test Notifications ...
[2023-01-22 10:35:25][tgtg][scanner.py:run:165][INFO] Scanner started ...

**Comment by Der-Henning** [comment] 2023-01-22 15:45
Hi @pershoot. The warning means, that the scanner received a 403 captcha error on a request. But the scanner managed to "repair" the session and continued working. That's why I changed the log level from "ERROR" to "WARNING".

**Comment by Der-Henning** [comment] 2023-01-22 15:46
@GrappaTV Thank you for the feedback. I couldn't test the current release in the long run. So let me know if you have any issues.

**Comment by Wolbaal** [comment] 2023-01-23 10:03
Hi, thanks for the update! Unfortunately I got the error: Captcha error 403!

**Comment by Der-Henning** [comment] 2023-01-23 11:18
@Wolbaal does the scanner continue working after the 10 minutes? In my case, I receive a 403 error every 3 to 4 hours and after the sleep time the scanner continues working.

**Comment by Wolbaal** [comment] 2023-01-23 11:24
Hi, it's showing directly after start:

![image](https://user-images.githubusercontent.com/103828692/214028113-fa72eece-ef70-46ae-9206-f528e27c925b.jpeg)

**Comment by Der-Henning** [comment] 2023-01-23 11:31
@Wolbaal Does the scanner stop working then? What happens after the 10 minutes? Do you receive the same warning again? For additional information, you can run the scanner in debug mode with `DEBUG=true` or `main.py -d`.

**Comment by Wolbaal** [comment] 2023-01-23 11:38
Hi, I will run now for the full 10 minutes but thought I got the same error.
I do not know how to do in debug mode or main py (just happy that I find out with your comments to do with stack :-) )

**Comment by Wolbaal** [comment] 2023-01-23 11:47
![image](https://user-images.githubusercontent.com/103828692/214032254-dca51fcc-f1f9-4cd8-8307-331dc1b6ffa2.jpeg)

**Comment by Wolbaal** [comment] 2023-01-23 11:48
Same "problem"

**Comment by Wolbaal** [comment] 2023-01-24 08:15
Hi, just see that there are much captcha errors. At different times:

![image](https://user-images.githubusercontent.com/103828692/214242017-07804a6e-7312-4f11-87ef-b1807b7973cd.png)

**Comment by GrappaTV** [comment] 2023-01-24 10:33
Hi,

 

I didn’t see any of these in the past 24 hrs on the 4 scanners I’m running (for family/friends). I only saw this:



Which is repaired by the scanner in a few seconds.

 

I did see the below error on all 4 scanners at exactly the same time, so I guess it was a problem on the TGTG API.



 

Hopefully this can help somehow 😊

 

Cheers

Roel

 

BTW: the “Buy me a Coffee” doesn’t work… 😉

 

Van: Wolbaal  ***@***.***> ***@***.*** 
Verzonden: Tuesday, 24 January 2023 09:16
Aan: Der-Henning/tgtg ***@***.***>
CC: GrappaTV ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Der-Henning/tgtg] TGTG API ERROR (Issue #246)

 

Hi, just see that there are much captcha errors. At different times:

 <https://user-images.githubusercontent.com/103828692/214242017-07804a6e-7312-4f11-87ef-b1807b7973cd.png>

**Comment by Wolbaal** [comment] 2023-01-24 15:50
Hi, can it be possible that it has to do with a new captcha they implemented? Just saw that it shows also up in the app (iOS).... like this one:

![image](https://user-images.githubusercontent.com/103828692/214340545-c6abd3b4-9b1b-4a2c-b073-97745f310347.png)

The 1.14.6 is continues till this morning trying to connect but with no success. Tried also older versions 1.14.3 and 1.14.4 but no luck.

**Comment by light-bit** [comment] 2023-01-24 18:29
> Hi, can it be possible that it has to do with a new captcha they implemented? Just saw that it shows also up in the app (iOS).... like this one:
> 
> ![image](https://user-images.githubusercontent.com/103828692/214340545-c6abd3b4-9b1b-4a2c-b073-97745f310347.png)
> 
> The 1.14.6 is continues trying to connect from this morning till now but with no success. Tried also older versions 1.14.3 and 1.14.4 but no luck.
> 
> Very curious if this kind of ReCAPTCHA can be passing by a script/bot. Hopefully it will not has bad future for the Tgtg scanner!

I've noticed this as well a few months ago. This captcha happens when there's too many 403s. What I did: stop the scanner for a few days, implement the cron schedule (I don't run it after 6pm until 7am). Never received any 403s anymore. I also stopped scanning on Sunday's fwiw, also by utilizing cron.

**Comment by Wolbaal** [comment] 2023-01-25 13:43
Hi, @light-bit thanks for your tips, but unfortunately Iam a noob in this and happy that this is running....

@Der-Henning thanks for the new update, after starting 1.14.7 everything running smoothly for now.

**Comment by Der-Henning** [comment] 2023-01-28 18:57
Thank you for the feedback. I guess it is working well for now. Closing.
Feel free to create a new issue if you have any further problems.

**Closed by Der-Henning** 2023-01-28 18:57 UTC
Labels: bug

**Comment by GrappaTV** [comment] 2023-01-29 11:48
Thanks Henning, it works perfect for me !!

 

BR

Roel

 

 

 

Van: Henning Merklinger ***@***.***> 
Verzonden: Saturday, 28 January 2023 19:58
Aan: Der-Henning/tgtg ***@***.***>
CC: GrappaTV ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Der-Henning/tgtg] TGTG API ERROR (Issue #246)

 

Thank you for the feedback. I guess it is working well for now. Closing.
Feel free to create a new issue if you have any further problems.
