### ISSUE TITLE
EMail notifications not working - test notification does work

### ISSUE THREAD

**Issue by digitalface** [Der-Henning/tgtg#67] opened 2022-03-25 17:45 UTC
As title

The initial test notification for Gmail email works on program start (docker) but notifications for actual stock doesn't seem to send an email

Debug enabled and result below:

`2022-03-25 17:34:11 INFO     Sending notifications for shopname - 1 bags available
2022-03-25 17:34:11 DEBUG    Sending Mail Notification
send: 'noop\r\n'
reply: b'451 4.4.2 Timeout - closing connection. do8-20020a170906c10800b006dfe4h7edc6sm2525244ejc.61 - gsmtp\r\n'
reply: retcode (451); Msg: b'4.4.2 Timeout - closing connection. do8-20020a170906220800b006dfe4d1edc6sm2525244ejc.61 - gsmtp'
send: 'mail FROM:<myemail@gmail.com> size=428\r\n'`

**Comment by digitalface** [comment] 2022-03-25 17:48
Latest version (downloaded and installed via docker today)

**Comment by Der-Henning** [comment] 2022-03-25 18:10
OK. I will have a look. I didn't use the mail notification for some time now, but I didn't change anything. It should work.
Can you confirm if this is a permanent issue or just a one-time issue with the Gmail SMTP server?

Just to check your SMTP settings. However, they should be correct when you receive the test email notification.

````
SMTP=true
SMTP_HOST=smtp.gmail.com
SMTP_PORT=465
SMTP_USERNAME=<yourmail@gmail.com>
SMTP_PASSWORD=<yourapppassword>
SMTP_TLS=true
SMTP_SENDER=<yourmail@gmail.com>
SMTP_RECIPIENT=<yourmail@gmail.com>
````

**Comment by Der-Henning** [comment] 2022-03-25 20:32
I could reproduce the issue. Will try to fix asap.

**Comment by digitalface** [comment] 2022-03-25 20:48
Thank you. Seems to be permanent, I've seen 5 notifications in console/log and attempts to email but none have worked.

**Comment by digitalface** [comment] 2022-03-25 21:17
..as an aside do you think it's possible to add Gotify notification?

**Comment by Der-Henning** [comment] 2022-03-25 21:24
You can use the Webhooks notifier to trigger your gofity server via REST API.

**Comment by Der-Henning** [comment] 2022-03-25 21:39
[6a03952](https://github.com/Der-Henning/tgtg/commit/6a039524858bea975ad2b4a2804003767a46fc46) added quick fix for the mail problem. Latest Docker image is updated and should work.
The underlying issue needs some more investigation.
I would appreciate any feedback.

**Comment by digitalface** [comment] 2022-03-25 22:59
> You can use the Webhooks notifier to trigger your gofity server via REST API.

I honestly wouldn't have a clue what do add to the webhook bit to get this to work. I have Gotify integration with Sonarr etc but all they ask for is the local Gotify server URL.

I'll try your new docker image and will let you know of any issues. Thanks again!

**Comment by Der-Henning** [comment] 2022-03-26 07:37
I didn't use Gotify, but this should work:
Based on [Gotify Push Message Documentation](https://gotify.net/docs/pushmsg)

Of cause you have to modify the Gotify server url.
`````
      - WEBHOOK=true
      - WEBHOOK_URL=https://push.example.de/message?token=<apptoken>
      - WEBHOOK_METHOD=POST
      - WEBHOOK_BODY={"message": "${{display_name}} - New Amount: ${{items_available}}", "priority": 2, "title": "New TGTG Items"}
      - WEBHOOK_TYPE=application/json
      - WEBHOOK_TIMEOUT=60
`````

**Comment by Der-Henning** [comment] 2022-03-26 18:45
On the latest docker image mail notification is working for me now. Can you confirm?

**Comment by digitalface** [comment] 2022-03-27 09:06
Hi, email notification is now working thanks! I'll check Gotify notification later today.

**Comment by digitalface** [comment] 2022-03-27 20:36
> I didn't use Gotify, but this should work: Based on [Gotify Push Message Documentation](https://gotify.net/docs/pushmsg)
> 
> Of cause you have to modify the Gotify server url.
> 
> ```
>       - WEBHOOK=true
>       - WEBHOOK_URL=https://push.example.de/message?token=<apptoken>
>       - WEBHOOK_METHOD=POST
>       - WEBHOOK_BODY={"message": "${{display_name}} - New Amount: ${{items_available}}", "priority": 2, "title": "New TGTG Items"}
>       - WEBHOOK_TYPE=application/json
>       - WEBHOOK_TIMEOUT=60
> ```
> 
> edit: In order for this to work, i had to make a change that was already planned [75e54df](https://github.com/Der-Henning/tgtg/commit/75e54dfed75d85fcdc81a5fbaacbc73fc9a30288) already mentioned in #50 Latest version should work.

Hi Der-Henning,

Docker-compose is complaining about the comma's in the WEBHOOK_BODY part of the code. I've checked on YAML parser website and it says

ERROR:

while parsing a block mapping
  in "<unicode string>", line 43, column 9:
          - WEBHOOK_BODY={"message": "${{dis ... 
            ^
expected <block end>, but found ','
  in "<unicode string>", line 43, column 88:
     ... ew Amount: ${{items_available}}", "priority": 2, "title": "New T ... 
                                         ^

**Comment by Der-Henning** [comment] 2022-03-28 06:29
Yes, sorry. In the docker compose file you have to wrap the environment variables containing special characters in ```''```.

````
- 'WEBHOOK_BODY={"message": "${{display_name}} - New Amount: ${{items_available}}", "priority": 2, "title": "New TGTG Items"}'
````

I used a ```.env``` file where the ```''``` is not required. You can insert ```.env``` files using

````
services:
  tgtg:
    image: derhenning/tgtg:latest
    env_file: 
      - .env
````

**Comment by Der-Henning** [comment] 2022-03-30 15:19
Can you please enable ```debug=true``` and post the log? It should contain something like

````
2022-03-30 17:17:04 DEBUG    Webhook url: https://<gotify.domain>/message?token=<apptoken>
2022-03-30 17:17:04 DEBUG    Webhook headers: {'Content-Type': 'application/json'}
2022-03-30 17:17:04 DEBUG    Webhook body: {"message": "test_item - New Amount: 1", "priority": 2, "title": "New TGTG Items"}
````

**Comment by digitalface** [comment] 2022-03-30 16:19
`2022-03-30 17:16:07 DEBUG    Webhook url: http://gotify/message?token=xxxxxx
2022-03-30 17:16:07 DEBUG    Webhook headers: {'Content-Type': 'application/json'}
2022-03-30 17:16:07 DEBUG    Webhook body: {"message": "} - New Amount: }", "priority": 2, "title": "New TGTG Items"}
2022-03-30 17:16:07 DEBUG    Starting new HTTP connection (1): gotify:80
2022-03-30 17:16:07 DEBUG    http://gotify:80 "POST /message?token=xxxxxx HTTP/1.1" 200 131
2022-03-30 17:16:07 INFO     Pret - TOWN (Dinner Bag) - new amount: 1`

**Comment by digitalface** [comment] 2022-03-30 16:22
My .env file contains

> WEBHOOK_BODY={"message": "${{display_name}} - New Amount: ${{items_available}}", "priority": 2, "title": "New TGTG Items"}
WEBHOOK=true
WEBHOOK_URL=http://gotify/message?token=xxxxxx
WEBHOOK_METHOD=POST
WEBHOOK_TYPE=application/json
WEBHOOK_TIMEOUT=60

**Comment by Der-Henning** [comment] 2022-03-30 16:32
Your config seems to be fine. Can you validate you are using the latest image? 
Stop the container and run `docker pull derhenning/tgtg:latest`.
On which OS/arch are you running the container?

**Comment by digitalface** [comment] 2022-03-30 17:42
Hi,
I'm using image 1.9.0 - I couldn't tell you if that was what I was running before as I've just updated all containers. I'll try it again. Am running on a Synology NAS DSM7.

**Comment by Der-Henning** [comment] 2022-03-30 18:39
I could reproduce the issue on a Raspberry 4 with Linux/aarch64. Same image with same config on Apple M1 is working fine.
Investigating ...

**Comment by Der-Henning** [comment] 2022-03-30 19:21
OK. I got it working. Using the `docker-compose.yml` file you have to escape the `$` signs.
````
- 'WEBHOOK_BODY={"message": "$${{display_name}} - New Amount: $${{items_available}}", "priority": 2, "title": "New TGTG Items"}'
````
I will add this to the documentation in the `docker-compose.yml`.
I didn't get it to work using the .env file though...

**Comment by digitalface** [comment] 2022-03-31 15:56
Yep I deleted my .env and put all the environmental variables in to my docker-compose.yml file and now I'm getting Gotify notifications. 

Thanks again :)

**Comment by Der-Henning** [comment] 2022-04-06 06:41
closing. If you have any other problems feel free to create a new issue.

**Closed by Der-Henning** 2022-04-06 06:41 UTC
