### ISSUE TITLE
Version 1.16.3 crashes when starting

### ISSUE THREAD

**Issue by news-github1** [Der-Henning/tgtg#358] opened 2023-06-03 10:23 UTC
Version 1.16.3 crashing when starting. The log keeps empty. Tried to start on multiple computers same result. 
"failed to execute script main "due" unhandled exception"
This is the day after the TGTG app has been updated.

**Comment by Der-Henning** [comment] 2023-06-03 11:27
Hi, @news-github1.
Could you please provide some more details. Do you use the pre-build executables, run from source or use docker? Which OS / Arch are you using? Does it start with the unchanged `config.ini`? Is a `scanner.log` file created?

**Comment by alpert1** [comment] 2023-06-04 11:02
I can confirm the issue running the latest docker image (v.1.16.3) on Ubuntu. After the initial notification it stops doing its job without any additional output, the console only says `Scanner started ...`.

When using a cron schedule it interestingly disables itself despite being within the active time:
`SCHEDULE_CRON=* 6-22 * * 1-7`
```
2023-06-04 12:53:45 INFO     Sending test Notifications ...
2023-06-04 12:53:46 INFO     Scanner started ...
2023-06-04 12:53:46 INFO     Active on schedule: Every minute, between 06:00 AM and 10:59 PM, Monday through Sunday
2023-06-04 12:53:46 INFO     Scanner disabled by cron schedule.
```

However, as stated, disabling the cron scheduler doesn't fix the scanner.

**Comment by Der-Henning** [comment] 2023-06-04 11:25
Hi @alpert1.
Did it really stop? You only receive any output when there are changes in the available amount of your observed magic bags. Run the scanner in debugging mode to see if the scanner updates the amounts correctly.

**Comment by alpert1** [comment] 2023-06-04 11:46
Sorry for the confusion! So the scanner itself continues to run.

It seems to behave correctly while the cron schedule is disabled. If I add a new offer with availavle bags to my favorites, this change is detected by the scanner, but no notification is being sent out. With the scanner from [marklagendijk](https://github.com/marklagendijk/node-toogoodtogo-watcher) I used to receive a notification in that case and it was my quick test method to check if everything was working. This doesn't seem to apply here, as this scanner seems to only notifies one if the offer had 0 bags available in the previous state.

However, when activating the cron schedule, the scanner doesn't check the tgtg-API during the active time. So this part seems to be an issue.

**Comment by Der-Henning** [comment] 2023-06-04 11:56
The scanner only works with weekdays from 0-6.
So the correct configuration would be `SCHEDULE_CRON=* 6-22 * * 0-6` or better `SCHEDULE_CRON=* 6-22 * * *`.
I see that the printed message in the log doesn't match to this behavior. I will try to fix that.

**Comment by Der-Henning** [comment] 2023-06-23 17:31
With Release v1.17.0 the scanner now checks for proper cron strings.
Closing.

**Closed by Der-Henning** 2023-06-23 17:31 UTC
